### PR TITLE
Update es-ES.hjson

### PR DESCRIPTION
**Pull request by T3sl4B0y**
By T3sl4B0y:) I would like to contribute to this mod...

### CODE REVIEW

**Comment by direwolf420** [comment]
Hi, thanks for translating the mod!
Just a small thing: remove all the `//` and `/* */`, that will make them actually translated ingame. After that, build the mod, and make a commit again, it will update this PR.

**Comment by direwolf420** [comment]
Thanks.
Regarding your commit message about Thorium, I haven't got any special programs to recommend, I just use notepad++ for editing text files.

**Comment by direwolf420** [comment]
What name would you want to be credited as? "T3sl4B0y"?

**Comment by T3sl4B0y** [comment]
Yep. T3sl4B0y.
And thank you very much, I'll try to make a mod to translate it.
If you need an update, or help with the translation of another mod. feel free to let me know

**Pull request merged**
